### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'kind') in 0.10.1

### ISSUE THREAD

**Issue by ntucker** [sandersn/downlevel-dts#81]
TypeScript 4.8.2
Worked in `downlevel-dts` v 0.10.0; broken in 0.10.1

```bash
/home/ntucker/src/rest-hooks/node_modules/downlevel-dts/node_modules/typescript/lib/typescript.js:28803
➤ YN0000:         return node.kind === 162 /* ComputedPropertyName */;
➤ YN0000:                     ^
➤ YN0000: 
➤ YN0000: TypeError: Cannot read properties of undefined (reading 'kind')
➤ YN0000:     at Object.isComputedPropertyName (/home/ntucker/src/rest-hooks/node_modules/downlevel-dts/node_modules/typescript/lib/typescript.js:28803:21)
➤ YN0000:     at Object.createPropertyDeclaration (/home/ntucker/src/rest-hooks/node_modules/downlevel-dts/node_modules/typescript/lib/typescript.js:23287:20)
➤ YN0000:     at transform (/home/ntucker/src/rest-hooks/node_modules/downlevel-dts/index.js:96:20)
➤ YN0000:     at visitNodes (/home/ntucker/src/rest-hooks/node_modules/downlevel-dts/node_modules/typescript/lib/typescript.js:89111:48)
➤ YN0000:     at Object.visitEachChild (/home/ntucker/src/rest-hooks/node_modules/downlevel-dts/node_modules/typescript/lib/typescript.js:89579:362)
➤ YN0000:     at transform (/home/ntucker/src/rest-hooks/node_modules/downlevel-dts/index.js:374:15)
➤ YN0000:     at visitNodes (/home/ntucker/src/rest-hooks/node_modules/downlevel-dts/node_modules/typescript/lib/typescript.js:89111:48)
➤ YN0000:     at visitLexicalEnvironment (/home/ntucker/src/rest-hooks/node_modules/downlevel-dts/node_modules/typescript/lib/typescript.js:89151:22)
➤ YN0000:     at Object.visitEachChild (/home/ntucker/src/rest-hooks/node_modules/downlevel-dts/node_modules/typescript/lib/typescript.js:89702:55)
➤ YN0000:     at transform (/home/ntucker/src/rest-hooks/node_modules/downlevel-dts/index.js:374:15)
```

**Comment by davidyuk** [comment]
I had the same problem! I think it stopped working after https://github.com/sandersn/downlevel-dts/commit/a1a8f5675a1a824529bee01d947eb00304bf6ac4. So downlevel-dts expects TS@4.9, I've updated my to 4.9.3 and it works now 🎉
